#!/bin/bash
set -e

# 安装自动启动程序
if [ -e /opt/appGtLabel/appGtLabel.desktop ];then
    cp -v /opt/appGtLabel/appGtLabel.desktop /usr/share/applications
fi

# 恢复配置相关文件
#if [ -e /var/E600_conf.tgz ];then
#    tar xPf /var/E600_conf.tgz
#    echo "conf files(/var/E600_conf.tgz) -> restorted."
#fi
