version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=Gz-123456
      - MYSQL_DATABASE=GzLabel
    ports:
      - 3318:3306
    volumes:
      - db:/var/lib/mysql
      - ./GzLabel.sql:/docker-entrypoint-initdb.d/init.sql #SQL 文件只在数据库首次初始化时生效，如果 db 卷里已经有数据，则不会重新执行。
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    depends_on:
      mysqldb:
        condition: service_healthy
    build: .
    restart: unless-stopped
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      - DATABASE_HOST=mysqldb
      - DB_USER=root
      - DB_PASSWORD=Gz-123456
      - DB_NAME=GzLabel
      - DB_PORT=3306
    stdin_open: true
    tty: true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes: 
  db:     #Docker 自动管理 数据存储位置 /var/lib/docker/volumes/db/_data
